apiVersion: containerapp.io/v1
kind: ContainerApp
metadata:
  name: jarvis-assistant
spec:
  location: eastus
  resourceGroup: jarvis-resource-group
  environmentId: jarvis-container-env
  
  template:
    containers:
    - name: jarvis-assistant
      image: jarviscontainerregistry.azurecr.io/jarvis-assistant:latest
      resources:
        cpu: 0.5
        memory: 1Gi
      
      env:
      - name: AZURE_ENV
        value: production
      
      - name: OPENAI_API_KEY
        secretRef: openai-api-key
      
      - name: DATABASE_URL
        secretRef: database-connection-string
      
      - name: JWT_SECRET
        secretRef: jwt-secret

  configuration:
    activeRevisionsMode: single
    
    secrets:
    - name: openai-api-key
      value: ${OPENAI_API_KEY}
    
    - name: database-connection-string
      value: ${DATABASE_CONNECTION_STRING}
    
    - name: jwt-secret
      value: ${JWT_SECRET}
    
    ingress:
      external: true
      targetPort: 8000
      
    registries:
    - server: jarviscontainerregistry.azurecr.io
      username: ${ACR_USERNAME}
      passwordSecretRef: acr-password
    
    secrets:
    - name: acr-password
      value: ${ACR_PASSWORD}
  
  scaling:
    minReplicas: 1
    maxReplicas: 3
    
    rules:
    - name: http-scaling
      http:
        metadata:
          concurrentRequests: 10
